### ISSUE TITLE
Some files missing

### ISSUE THREAD

**Issue by PAMinerva** [Sunset-Studios/Sunset#6]
Hi, I noticed that the .gitignore file excludes SUN files, which prevents the project from being compiled. 
Is this intentional, or is it something that can be fixed?

**Comment by gitbetter** [comment]
Hey! The .SUN format is a custom engine format for cooked assets. I don't check these in for the same reason you don't usually check in the precompiled binaries for a project: they can be large and instead can be cooked locally.

Try building the **CookerRun** target in Visual Studio, as that will cook all demo and engine assets into their .SUN format equivalents.

I will add some instructions to that effect in the README, thanks for pointing it out!

**Comment by PAMinerva** [comment]
Oh, it worked!
I was able to compile and run the demo.
Thank you!
